apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: realtime
spec:
  selector:
    app: chat-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
