apiVersion: v1
kind: Service
metadata:
  name: gift-service
  namespace: core
spec:
  selector:
    app: gift-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
