apiVersion: v1
kind: Service
metadata:
  name: moderation-service
  namespace: admin
spec:
  selector:
    app: moderation-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
