apiVersion: v1
kind: Namespace
metadata:
  name: core

---
apiVersion: v1
kind: Namespace
metadata:
  name: realtime

---
apiVersion: v1
kind: Namespace
metadata:
  name: infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: admin
